# Generated by Django 2.1.5 on 2019-02-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('standard', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('phone_number', models.CharField(max_length=13)),
                ('stream', models.CharField(blank=True, max_length=20)),
                ('area', models.CharField(blank=True, max_length=40)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('karma_point', models.CharField(blank=True, max_length=40)),
                ('email', models.CharField(blank=True, max_length=60)),
                ('photo', models.CharField(blank=True, max_length=300)),
                ('goal', models.CharField(blank=True, max_length=10)),
                ('school', models.CharField(blank=True, max_length=100)),
                ('coachings', models.CharField(blank=True, max_length=500)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateTimeField(blank=True)),
                ('language', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'db_table': 'classcast_user_info',
            },
        ),
    ]
