# Generated by Django 2.1.5 on 2019-02-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190216_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
