# Generated by Django 2.1.5 on 2019-02-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190216_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='month',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='1', max_length=9),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='standard',
            field=models.IntegerField(blank=True),
        ),
    ]
