# Generated by Django 2.1.5 on 2019-02-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190217_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='month',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='1', max_length=9),
        ),
    ]
