# Generated by Django 2.1.5 on 2019-02-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190217_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='date_joined',
            field=models.DateTimeField(),
        ),
    ]
