# Generated by Django 2.1.5 on 2019-02-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190217_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='standard',
            field=models.CharField(choices=[('1', '9'), ('2', '10'), ('3', '11'), ('4', '12'), ('5', '')], default='5', max_length=5),
        ),
    ]
