# Generated by Django 2.1.5 on 2019-02-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190217_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
