# Generated by Django 2.1.5 on 2019-02-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190218_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionSagar',
            fields=[
                ('xblock_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('goal', models.CharField(max_length=40)),
                ('standard', models.IntegerField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=20)),
                ('chapter', models.CharField(blank=True, max_length=50)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('questionType', models.CharField(blank=True, max_length=10)),
                ('difficulty', models.IntegerField(blank=True)),
            ],
        ),
    ]
