# Generated by Django 2.1.5 on 2019-02-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_questionsagar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionsagar',
            table='questionSagar',
        ),
    ]
