# Generated by Django 2.1.5 on 2019-02-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190222_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classcast_test_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_attempts', models.IntegerField()),
                ('num_skips', models.IntegerField()),
                ('num_incorrect_attempts', models.IntegerField()),
                ('average_time_attempt', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
                ('xblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.questionSagar')),
            ],
            options={
                'db_table': 'classcast_test_submissions',
            },
        ),
    ]
