# Generated by Django 2.1.5 on 2019-02-26 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_classcast_test_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classcast_question_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted', models.IntegerField()),
                ('correctly_attempted', models.IntegerField()),
                ('num_skips', models.IntegerField()),
                ('time_taken', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('correctly_attempted_in_test', models.BooleanField()),
                ('correctly_attempted_in_gym', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
                ('xblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.questionSagar')),
            ],
            options={
                'db_table': 'classcast_question_submissions',
            },
        ),
        migrations.RenameField(
            model_name='classcast_test_submission',
            old_name='num_attempts',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='classcast_test_submission',
            old_name='average_time_attempt',
            new_name='time_taken',
        ),
        migrations.RemoveField(
            model_name='classcast_test_submission',
            name='num_incorrect_attempts',
        ),
        migrations.RemoveField(
            model_name='classcast_test_submission',
            name='num_skips',
        ),
        migrations.RemoveField(
            model_name='classcast_test_submission',
            name='xblock',
        ),
        migrations.AddField(
            model_name='classcast_test_submission',
            name='chapter',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='classcast_test_submission',
            name='subject',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
