# Generated by Django 2.1.5 on 2019-02-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190226_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classcast_question_submission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classcast_question_submission',
            name='xblock',
        ),
        migrations.RemoveField(
            model_name='classcast_test_submission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Classcast_question_submission',
        ),
        migrations.DeleteModel(
            name='Classcast_test_submission',
        ),
        migrations.DeleteModel(
            name='questionSagar',
        ),
    ]
