# Generated by Django 2.1.5 on 2019-04-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190226_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='standard',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '')], default='14', max_length=5),
        ),
    ]
