# Generated by Django 2.1.5 on 2019-07-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190420_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='standard',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', 'SSC'), ('15', 'Bank PO'), ('16', 'Railways'), ('17', 'Bank Clerk'), ('18', '')], default='18', max_length=5),
        ),
    ]
