# Generated by Django 2.1.5 on 2019-07-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190711_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_info',
            fields=[
                ('exam_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=40)),
                ('subjects', models.CharField(blank=True, max_length=500)),
                ('exam_type', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
