# Generated by Django 2.1.5 on 2019-07-31 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_exam_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='parents_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relationship_to_student', models.CharField(choices=[('1', 'Father'), ('2', 'Mother'), ('3', 'Brother'), ('4', 'Other')], default='4', max_length=15)),
                ('contact_number', models.CharField(max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
            ],
        ),
    ]
