# Generated by Django 2.1.5 on 2019-07-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_parents_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
