# Generated by Django 2.1.5 on 2019-07-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190731_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents_details',
            name='relationship_to_student',
            field=models.CharField(choices=[('1', 'Father'), ('2', 'Mother'), ('3', 'Brother'), ('4', 'Sister'), ('5', 'Other')], default='5', max_length=15),
        ),
    ]
