# Generated by Django 2.2.4 on 2020-01-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200106_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='standard',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', 'SSC'), ('15', 'Bank PO'), ('16', 'Railways'), ('17', 'Bank Clerk'), ('18', 'IIT JAM'), ('19', 'NET JRF'), ('20', 'TIFR'), ('21', 'KVS TGT/PGT'), ('22', 'NVSNVS TGT/PGT'), ('23', 'DSSSB TGT/PGT'), ('24', 'APSAPS TGT/PGT'), ('25', 'UGC NET'), ('26', 'GATE'), ('27', 'UPPRPB'), ('28', 'UP LT'), ('29', '')], default='18', max_length=5),
        ),
    ]
