# Generated by Django 2.2.2 on 2019-06-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('content_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('content_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyModel',
            fields=[
                ('key_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=22)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license_provider.ContentModel')),
            ],
        ),
    ]
