# Generated by Django 2.2.2 on 2019-06-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
