# Generated by Django 2.2.2 on 2019-06-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license_provider', '0002_contentmodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymodel',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='license_provider.ContentModel'),
        ),
    ]
