# Generated by Django 2.1.5 on 2019-02-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_auto_20190217_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_info',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default=0, max_length=40)),
                ('lastname', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(default=0, max_length=40)),
                ('classes', models.CharField(default=0, max_length=40)),
                ('photo', models.CharField(blank=True, max_length=100)),
                ('coaching_name', models.CharField(blank=True, max_length=40)),
                ('qualification', models.CharField(blank=True, max_length=250)),
                ('area', models.CharField(default=0, max_length=40)),
                ('pincode', models.CharField(max_length=10)),
                ('goal', models.CharField(blank=True, max_length=50)),
                ('rating', models.IntegerField(blank=True)),
                ('oneliner', models.CharField(blank=True, max_length=250)),
                ('courses', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_student_interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=0)),
                ('is_active', models.BooleanField(default=0)),
                ('batch_id', models.CharField(default='', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_left', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user_info')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachers.teacher_info')),
            ],
        ),
    ]
