# Generated by Django 2.1.5 on 2019-02-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20190217_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_info',
            name='pincode',
        ),
    ]
