# Generated by Django 2.1.5 on 2019-02-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_remove_teacher_info_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_info',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
