# Generated by Django 2.1.5 on 2019-02-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190217_1335'),
        ('teachers', '0004_teacher_info_pincode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacher_student_interaction',
            unique_together={('student', 'teacher')},
        ),
    ]
