# Generated by Django 2.1.5 on 2019-02-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20190217_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_student_interaction',
            name='batch_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
