# Generated by Django 2.1.5 on 2019-02-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190218_1814'),
        ('teachers', '0006_auto_20190218_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_course_interactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(blank=True, max_length=60)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
            ],
        ),
    ]
