# Generated by Django 2.1.5 on 2019-02-21 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190218_1814'),
        ('teachers', '0007_student_course_interactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=60)),
                ('is_enrollment', models.BooleanField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
            ],
        ),
        migrations.RemoveField(
            model_name='student_course_interactions',
            name='student',
        ),
        migrations.RenameField(
            model_name='teacher_info',
            old_name='oneliner',
            new_name='about',
        ),
        migrations.AddField(
            model_name='teacher_info',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='1', max_length=9),
        ),
        migrations.DeleteModel(
            name='student_course_interactions',
        ),
    ]
