# Generated by Django 2.1.5 on 2019-02-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_auto_20190221_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_enrollment',
            old_name='is_enrollment',
            new_name='is_enrolled',
        ),
    ]
