# Generated by Django 2.1.5 on 2019-02-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_auto_20190221_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_enrollment',
            name='batch',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='teacher_info',
            name='batches',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teacher_student_interaction',
            name='batch',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='teacher_info',
            name='courses',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
