# Generated by Django 2.1.5 on 2019-02-27 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_auto_20190227_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_enrollment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher_student_interaction'),
        ),
    ]
