# Generated by Django 2.1.5 on 2019-02-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_auto_20190227_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_student_interaction',
            name='batch',
        ),
        migrations.AlterField(
            model_name='teacher_student_interaction',
            name='batch_id',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
