# Generated by Django 2.1.5 on 2019-02-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_auto_20190227_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_info',
            name='teacher_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
