# Generated by Django 2.1.5 on 2019-04-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_code',
            name='batch_id',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='access_code',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
