# Generated by Django 2.1.5 on 2019-05-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_auto_20190417_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_info',
            name='classcast_select',
            field=models.BooleanField(default=False),
        ),
    ]
