# Generated by Django 2.1.5 on 2019-05-09 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_teacher_info_classcast_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_code',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
