# Generated by Django 2.1.5 on 2019-05-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_access_code_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_info',
            name='Type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
