# Generated by Django 2.1.5 on 2019-05-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_teacher_info_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_info',
            name='Type',
        ),
    ]
