# Generated by Django 2.2.4 on 2019-10-16 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190731_1506'),
        ('teachers', '0019_remove_teacher_info_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_crashcourse_enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher_info')),
            ],
            options={
                'unique_together': {('student', 'teacher')},
            },
        ),
    ]
