# Generated by Django 2.2.4 on 2019-10-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190731_1506'),
        ('teachers', '0020_student_crashcourse_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_crashcourse_enrollment',
            name='course_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='student_crashcourse_enrollment',
            unique_together={('student', 'teacher', 'course_id')},
        ),
    ]
