# Generated by Django 2.2.4 on 2019-10-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190731_1506'),
        ('teachers', '0021_auto_20191016_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_crashcourse_enrollment',
            new_name='crashcourse_enrollment',
        ),
    ]
