# Generated by Django 2.2.4 on 2019-10-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0022_auto_20191016_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crashcourse_enrollment',
        ),
    ]
