# Generated by Django 2.1.5 on 2019-05-25 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0019_remove_teacher_info_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_account',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Type', models.CharField(default=0, max_length=40)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher_info')),
            ],
        ),
    ]
