# Generated by Django 2.1.5 on 2019-05-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_remove_teacher_info_type'),
        ('teachers_app', '0002_auto_20190526_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_batch_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(default='Batch-1', max_length=40)),
                ('standard', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '')], default='14', max_length=5)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher_info')),
            ],
        ),
        migrations.DeleteModel(
            name='batch',
        ),
        migrations.AlterUniqueTogether(
            name='teacher_batch_data',
            unique_together={('teacher', 'batch_id', 'standard')},
        ),
    ]
