# Generated by Django 2.1.5 on 2019-05-26 20:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190420_2234'),
        ('teachers_app', '0003_auto_20190526_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_attendance_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_attended', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers_app.teacher_batch_data')),
            ],
        ),
    ]
