# Generated by Django 2.1.5 on 2019-05-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0004_class_attendance_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_attendance_data',
            old_name='teacher',
            new_name='batch',
        ),
    ]
