# Generated by Django 2.1.5 on 2019-05-26 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0005_auto_20190527_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_attendance_data',
            name='timestamp',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
