# Generated by Django 2.1.5 on 2019-05-26 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0006_auto_20190527_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_attendance_data',
            name='timestamp',
            field=models.DateField(blank=True, default=datetime.date(2019, 5, 27)),
        ),
    ]
