# Generated by Django 2.1.5 on 2019-05-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190420_2234'),
        ('teachers_app', '0007_auto_20190527_0151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class_attendance_data',
            unique_together={('student', 'batch', 'timestamp')},
        ),
    ]
