# Generated by Django 2.1.5 on 2019-06-14 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0008_auto_20190527_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_batch_data',
            name='class_end_timing',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='teacher_batch_data',
            name='class_start_timing',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='teacher_batch_data',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher_batch_data',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher_batch_data',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher_batch_data',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher_batch_data',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher_batch_data',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher_batch_data',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class_attendance_data',
            name='timestamp',
            field=models.DateField(blank=True, default=datetime.date(2019, 6, 14)),
        ),
    ]
