# Generated by Django 2.1.5 on 2019-06-28 11:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0009_auto_20190614_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='fcm_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcmToken', models.CharField(blank=True, max_length=5000)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers_app.teacher_account')),
            ],
        ),
        migrations.AlterField(
            model_name='class_attendance_data',
            name='timestamp',
            field=models.DateField(blank=True, default=datetime.date(2019, 6, 28)),
        ),
    ]
