# Generated by Django 2.1.5 on 2019-06-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0010_auto_20190628_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fcm_token',
            new_name='fcm_token_teacher',
        ),
    ]
