# Generated by Django 2.2.4 on 2019-08-15 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_remove_teacher_info_type'),
        ('teachers_app', '0018_auto_20190731_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_attendance_data',
            name='timestamp',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 15)),
        ),
        migrations.CreateModel(
            name='teacher_credentials',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(default=0, max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher_info')),
            ],
        ),
    ]
