# Generated by Django 2.2.4 on 2019-09-28 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0019_auto_20190815_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_attendance_data',
            name='timestamp',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 28)),
        ),
        migrations.AlterField(
            model_name='teacher_batch_data',
            name='standard',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', 'SSC'), ('15', 'Bank PO'), ('16', 'Railways'), ('17', 'Bank Clerk'), ('18', '')], default='14', max_length=5),
        ),
    ]
