# Generated by Django 2.2.4 on 2019-10-16 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0021_auto_20190928_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_attendance_data',
            name='timestamp',
            field=models.DateField(blank=True, default=datetime.date(2019, 10, 16)),
        ),
    ]
