# Generated by Django 2.2.4 on 2019-10-18 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0022_auto_20191016_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_attendance_data',
            name='timestamp',
            field=models.DateField(blank=True, default=datetime.date(2019, 10, 18)),
        ),
    ]
