# Generated by Django 2.2.4 on 2020-01-06 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0027_auto_20191214_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_attendance_data',
            name='timestamp',
            field=models.DateField(blank=True, default=datetime.date(2020, 1, 6)),
        ),
    ]
