# Generated by Django 2.2.4 on 2020-02-08 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0037_auto_20200130_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_attendance_data',
            name='timestamp',
            field=models.DateField(blank=True, default=datetime.date(2020, 2, 8)),
        ),
    ]
