# Generated by Django 2.1.5 on 2019-04-10 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_auto_20190226_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='fcm_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcmToken', models.CharField(blank=True, max_length=5000)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
            ],
        ),
    ]
