# Generated by Django 2.1.5 on 2019-04-19 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190226_1209'),
        ('device_id', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='device_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
            ],
        ),
        migrations.RemoveField(
            model_name='fcm_token',
            name='student',
        ),
        migrations.DeleteModel(
            name='fcm_token',
        ),
    ]
