# Generated by Django 2.2.4 on 2019-12-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0023_delete_crashcourse_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=40)),
                ('course_details', models.CharField(blank=True, max_length=500)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher_info')),
            ],
        ),
    ]
