# Generated by Django 2.2.4 on 2019-12-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chapter_details',
            fields=[
                ('chapter_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='white_label.course_details')),
            ],
        ),
    ]
