# Generated by Django 2.2.4 on 2019-12-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0002_chapter_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='course_details',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
