# Generated by Django 2.2.4 on 2019-12-08 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190731_1506'),
        ('white_label', '0003_auto_20191208_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_course_interactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_method', models.CharField(choices=[('Payment', 'Payment'), ('Token', 'Token')], default='Token', max_length=32)),
                ('payement_mode', models.CharField(blank=True, max_length=40)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='white_label.course_details')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
            ],
        ),
    ]
