# Generated by Django 2.2.4 on 2019-12-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0004_student_course_interactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_course_interactions',
            name='enrollment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
