# Generated by Django 2.2.4 on 2019-12-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0005_student_course_interactions_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter_details',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
