# Generated by Django 2.2.4 on 2019-12-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0006_chapter_details_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter_details',
            name='chapter_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
