# Generated by Django 2.2.4 on 2019-12-09 08:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190731_1506'),
        ('white_label', '0007_chapter_details_chapter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='access_code_coursewise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=10000)),
                ('batch_id', models.CharField(blank=True, max_length=60)),
                ('expired', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='white_label.course_details')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
            ],
        ),
    ]
