# Generated by Django 2.2.4 on 2019-12-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0008_access_code_coursewise'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter_details',
            name='chapter_details',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
