# Generated by Django 2.2.4 on 2019-12-13 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0009_chapter_details_chapter_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_package',
            fields=[
                ('package_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('thumbnail', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='package_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=500)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='white_label.course_details')),
                ('selected_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='white_label.course_package')),
            ],
        ),
    ]
