# Generated by Django 2.2.4 on 2019-12-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0023_delete_crashcourse_enrollment'),
        ('white_label', '0010_course_package_package_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_package',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher_info'),
        ),
    ]
