# Generated by Django 2.2.4 on 2019-12-14 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0011_course_package_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_package',
            name='course_on_display',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='white_label.course_details'),
        ),
    ]
