# Generated by Django 2.2.4 on 2019-12-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0012_course_package_course_on_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='amount_course_plus_books',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='course_details',
            name='amount_only_books',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='course_details',
            name='books_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_course_interactions',
            name='course_package',
            field=models.CharField(choices=[('course', 'course'), ('course_plus_books', 'course_plus_books'), ('only_books', 'only_books')], default='course', max_length=50),
        ),
    ]
