# Generated by Django 2.2.4 on 2019-12-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0013_auto_20191214_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='course_details',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
