# Generated by Django 2.2.4 on 2020-01-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0014_auto_20191214_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter_details',
            name='chapter_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course_details',
            name='course_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
