# Generated by Django 2.2.4 on 2020-01-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0015_auto_20200106_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='access_token_only',
            field=models.BooleanField(default=False),
        ),
    ]
