# Generated by Django 2.2.4 on 2020-01-13 12:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0023_delete_crashcourse_enrollment'),
        ('white_label', '0016_course_details_access_token_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_series_details',
            fields=[
                ('test_series_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('test_series_name', models.CharField(max_length=40)),
                ('test_series_details', models.CharField(blank=True, max_length=2000)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('access_token_only', models.BooleanField(default=False)),
                ('thumbnail', models.CharField(blank=True, max_length=1000)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher_info')),
            ],
        ),
        migrations.CreateModel(
            name='test_details',
            fields=[
                ('test_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('test_name', models.CharField(blank=True, max_length=100)),
                ('test_details', models.CharField(blank=True, max_length=500)),
                ('thumbnail', models.CharField(blank=True, max_length=1000)),
                ('free', models.BooleanField(default=False)),
                ('no_of_questions', models.IntegerField(default=0)),
                ('pos_marks', models.IntegerField(default=4)),
                ('neg_marks', models.IntegerField(default=-1)),
                ('negative_marking', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('test_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='white_label.test_series_details')),
            ],
        ),
    ]
