# Generated by Django 2.2.4 on 2020-01-14 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200106_2033'),
        ('white_label', '0017_test_details_test_series_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_test_interactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_method', models.CharField(choices=[('Payment', 'Payment'), ('Token', 'Token')], default='Token', max_length=32)),
                ('payement_mode', models.CharField(blank=True, max_length=40)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('enrollment_status', models.CharField(blank=True, max_length=50)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
                ('test_series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='white_label.test_series_details')),
            ],
        ),
    ]
