# Generated by Django 2.2.4 on 2020-01-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0018_student_test_interactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_details',
            name='duration',
            field=models.IntegerField(default=1800),
        ),
    ]
