# Generated by Django 2.2.4 on 2020-01-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0019_test_details_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_series_videos',
            fields=[
                ('course_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('free', models.BooleanField(default=False)),
                ('test_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='white_label.test_series_details')),
            ],
        ),
    ]
