# Generated by Django 2.2.4 on 2020-01-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0020_test_series_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_details',
            name='neg_marks',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='test_details',
            name='pos_marks',
            field=models.FloatField(default=1),
        ),
    ]
