# Generated by Django 2.2.4 on 2020-01-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0021_auto_20200124_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_series_details',
            name='thumbnail_free_test',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
