# Generated by Django 2.2.4 on 2020-01-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0022_test_series_details_thumbnail_free_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_test_series_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='white_label.course_details')),
                ('test_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='white_label.test_series_details')),
            ],
        ),
    ]
