# Generated by Django 2.2.4 on 2020-01-28 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0023_course_test_series_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_package_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=100)),
                ('package_details', models.CharField(blank=True, max_length=500)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='white_label.course_details')),
            ],
        ),
    ]
