# Generated by Django 2.2.4 on 2020-01-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0024_course_package_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_package_details',
            name='package_id',
            field=models.CharField(default='VG2TCD', max_length=20),
        ),
    ]
