# Generated by Django 2.2.4 on 2020-01-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0025_course_package_details_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_course_interactions',
            name='package',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course_package_details',
            name='package_id',
            field=models.CharField(default='N6W086', max_length=20),
        ),
    ]
