# Generated by Django 2.2.4 on 2020-01-29 07:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200106_2033'),
        ('white_label', '0026_auto_20200129_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_package_details',
            name='package_id',
            field=models.CharField(default='KWB95H', max_length=20),
        ),
        migrations.CreateModel(
            name='access_code_test_series_wise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=10000)),
                ('batch_id', models.CharField(blank=True, max_length=60)),
                ('expired', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
                ('test_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='white_label.test_series_details')),
            ],
        ),
    ]
