# Generated by Django 2.2.4 on 2020-01-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0027_auto_20200129_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_package_details',
            name='package_id',
            field=models.CharField(default='ZMJFEC', max_length=20),
        ),
    ]
