# Generated by Django 2.2.4 on 2020-01-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0028_auto_20200130_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_series_details',
            name='free_test_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test_series_details',
            name='paid_test_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course_package_details',
            name='package_id',
            field=models.CharField(default='HTSQW5', max_length=20),
        ),
    ]
