# Generated by Django 2.2.4 on 2020-02-08 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0029_auto_20200130_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_details',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 12, 18, 13, 137968)),
        ),
        migrations.AddField(
            model_name='test_details',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='course_package_details',
            name='package_id',
            field=models.CharField(default='83OBV0', max_length=20),
        ),
    ]
