# Generated by Django 2.2.4 on 2020-02-12 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_label', '0030_auto_20200208_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_details',
            name='assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course_package_details',
            name='package_id',
            field=models.CharField(default='V51LXU', max_length=20),
        ),
        migrations.AlterField(
            model_name='test_details',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 15, 4, 16, 769393)),
        ),
    ]
