# Generated by Django 2.2.4 on 2020-02-18 08:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0023_delete_crashcourse_enrollment'),
        ('users', '0022_auto_20200130_1242'),
        ('white_label', '0031_auto_20200212_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_package_details',
            name='package_id',
            field=models.CharField(default='H2TLSZ', max_length=20),
        ),
        migrations.AlterField(
            model_name='test_details',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 13, 48, 44, 815048)),
        ),
        migrations.CreateModel(
            name='access_code_premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=10000)),
                ('batch_id', models.CharField(blank=True, max_length=60)),
                ('expired', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher_info')),
            ],
        ),
    ]
