from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^add_course_enrollment/$', views.add_course_enrollment.as_view(), name='add_course_enrollment'),
	url(r'^add_course_enrollment_new/$', views.add_course_enrollment_new.as_view(), name='add_course_enrollment_new'),
	url(r'^get_course_list_shyam/$', views.get_course_list_shyam.as_view(), name='get_course_list_shyam'),
	url(r'^get_cahpter_list_shyam/(?P<course_id>[a-zA-Z0-9_.-]+)/$', views.get_cahpter_list_shyam.as_view(), name='get_cahpter_list_shyam'),
	url(r'^get_course_list/(?P<teacher_id>[a-zA-Z0-9_.-]+)/$', views.get_course_list.as_view(), name='get_course_list'),
	url(r'^get_my_course_list/(?P<teacher_id>[a-zA-Z0-9_.-]+)/$', views.get_my_course_list.as_view(), name='get_my_course_list'),
	url(r'^enrollment_from_token/$', views.enrollment_from_token.as_view(), name='enrollment_from_token'),
	url(r'^enrollment_from_token_new/$', views.enrollment_from_token_new.as_view(), name='enrollment_from_token_new'),
	url(r'^generateaccesscode/(?P<course_id>[a-zA-Z0-9_.-]+)/(?P<teacher_id>[a-zA-Z0-9_.-]+)/(?P<batch_id>[a-zA-Z0-9_.-]+)/(?P<number>[a-zA-Z0-9_.-]+)/$', views.generateAccessCode.as_view(), name='generateAccessCode'),
	url(r'^get_test_series_list/(?P<teacher_id>[a-zA-Z0-9_.-]+)/$', views.get_test_series_list.as_view(), name='get_test_series_list'),
	url(r'^get_test_list/(?P<test_series_id>[a-zA-Z0-9_.-]+)/$', views.get_test_list.as_view(), name='get_test_list'),
	url(r'^get_test_data/(?P<test_id>[a-zA-Z0-9_.-]+)/$', views.get_test_data, name='get_test_data'),
	url(r'^add_test_enrollment/$', views.add_test_enrollment.as_view(), name='add_test_enrollment'),
	url(r'^store_test_performance/$', views.store_test_performance, name='store_test_performance'),
    url(r'^get_previous_records/(?P<test_id>[a-zA-Z0-9_.-]+)/$', views.get_previous_records, name='get_previous_records'),
    url(r'^get_previous_records_all/(?P<teacher_id>[a-zA-Z0-9_.-]+)/$', views.get_previous_records_all, name='get_previous_records_all'),
    url(r'^get_test_series_courses/(?P<test_series_id>[a-zA-Z0-9_.-]+)/$', views.get_test_series_courses.as_view(), name='get_test_series_courses'),
    url(r'^add_test/$', views.add_test, name='add_test'),
    url(r'^get_course_test_series_list/(?P<course_id>[a-zA-Z0-9_.-]+)/$', views.get_course_test_series_list.as_view(), name='get_course_test_series_list'),
    url(r'^get_packages/(?P<course_id>[a-zA-Z0-9_.-]+)/$', views.get_packages.as_view(), name='get_packages'),
    url(r'^add_course_enrollment_with_package/$', views.add_course_enrollment_with_package.as_view(), name='add_course_enrollment_with_package'),
    url(r'^enrollment_from_token_test_series/$', views.enrollment_from_token_test_series.as_view(), name='enrollment_from_token_test_series'),
    url(r'^add_chapter/$', views.add_chapter, name='add_chapter'),
    url(r'^get_overall_permormance/(?P<teacher_id>[a-zA-Z0-9_.-]+)/$', views.get_overall_permormance, name='get_overall_permormance'),
    url(r'^get_student_list_ta/$', views.get_student_list_ta.as_view(), name='get_student_list_ta'),
    url(r'^get_student_performance_ta/(?P<student_username>[a-zA-Z0-9_.-]+)/$', views.get_student_performance_ta.as_view(), name='get_student_performance_ta'),
    url(r'^get_test_list_ta/$', views.get_test_list_ta.as_view(), name='get_test_list_ta'),
    url(r'^get_test_info_ta/(?P<test_id>[a-zA-Z0-9_.-]+)/$', views.get_test_info_ta.as_view(), name='get_test_info_ta'),
    url(r'^teacher_data_ts/$', views.teacher_data_ts.as_view(), name='teacher_data_ts'),
    url(r'^get_all_course_list_ta/$', views.get_all_course_list_ta.as_view(), name='get_all_course_list_ta'),
    url(r'^get_chapters_ta/(?P<course_id>[a-zA-Z0-9_.-]+)/$', views.get_chapters_ta.as_view(), name='get_chapters_ta'),
    url(r'^get_all_performance_ta/$', views.get_all_performance_ta.as_view(), name='get_all_performance_ta'),
    url(r'^get_student_list_coursewise_ta/(?P<course_id>[a-zA-Z0-9_.-]+)/$', views.get_student_list_coursewise_ta.as_view(), name='get_student_list_coursewise_ta'),
    url(r'^edit_student_data/(?P<student_username>[a-zA-Z0-9_.-]+)/$', views.edit_student_data.as_view(), name='edit_student_data'),
    url(r'^get_premium/$', views.get_premium, name='get_premium'),
]

