# Generated by Django 2.1.5 on 2019-04-08 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_auto_20190226_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('standard', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('chapter', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='classcast_question',
            fields=[
                ('xblock_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('goal', models.CharField(blank=True, max_length=40)),
                ('standard', models.IntegerField(blank=True, default=0)),
                ('subject', models.CharField(blank=True, max_length=20)),
                ('chapter', models.CharField(blank=True, max_length=50)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.IntegerField(blank=True, default=1)),
                ('marks', models.IntegerField(blank=True, default=3)),
                ('negativeMarks', models.IntegerField(blank=True, default=-1)),
                ('questionType', models.CharField(blank=True, max_length=20)),
                ('tags', models.CharField(default=None, max_length=1000)),
                ('question', models.CharField(default=None, max_length=5000)),
                ('option1', models.CharField(default=None, max_length=2000)),
                ('option2', models.CharField(default=None, max_length=2000)),
                ('option3', models.CharField(default=None, max_length=2000)),
                ('option4', models.CharField(default=None, max_length=2000)),
                ('option1_iscorrect', models.BooleanField(default=0)),
                ('option2_iscorrect', models.BooleanField(default=0)),
                ('option3_iscorrect', models.BooleanField(default=0)),
                ('option4_iscorrect', models.BooleanField(default=0)),
                ('explanation', models.CharField(blank=True, default=None, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Classcast_test_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('n_questions', models.IntegerField(blank=True, default='0')),
                ('time_taken', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_data.chapter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
            ],
            options={
                'db_table': 'classcast_test_submissions',
            },
        ),
        migrations.CreateModel(
            name='questionSagar',
            fields=[
                ('xblock_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('goal', models.CharField(max_length=40)),
                ('standard', models.IntegerField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=20)),
                ('chapter', models.CharField(blank=True, max_length=50)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('questionType', models.CharField(blank=True, max_length=10)),
                ('difficulty', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'questionSagar',
            },
        ),
        migrations.CreateModel(
            name='student_block_interactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default='None', max_length=15)),
                ('block', models.CharField(max_length=70)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
            ],
            options={
                'db_table': 'student_block_interactions',
            },
        ),
        migrations.CreateModel(
            name='student_topic_interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField()),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('attempted', models.IntegerField()),
                ('correctly_attempted', models.IntegerField()),
                ('num_skips', models.IntegerField()),
                ('time_taken', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attempted_in_test', models.BooleanField()),
                ('attempted_in_gym', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
                ('xblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_data.questionSagar')),
            ],
            options={
                'db_table': 'student_topic_interaction',
            },
        ),
        migrations.CreateModel(
            name='topics',
            fields=[
                ('topic_name', models.CharField(max_length=255)),
                ('topic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_data.chapter')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('standard', 'subject', 'chapter')},
        ),
    ]
