# Generated by Django 2.1.5 on 2019-04-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_block_interactions',
            name='block',
            field=models.CharField(max_length=300),
        ),
    ]
