# Generated by Django 2.1.5 on 2019-05-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0002_auto_20190419_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_block_interactions',
            name='n_questions',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='student_block_interactions',
            name='review',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
