# Generated by Django 2.1.5 on 2019-05-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0003_auto_20190509_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_block_interactions',
            name='n_questions',
        ),
        migrations.AddField(
            model_name='student_block_interactions',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
