# Generated by Django 2.1.5 on 2019-05-09 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0004_auto_20190509_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcast_test_submission',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='student_block_interactions',
            name='rating',
            field=models.IntegerField(default='0'),
        ),
    ]
