# Generated by Django 2.1.5 on 2019-05-09 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0005_auto_20190509_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_block_interactions',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
