# Generated by Django 2.1.5 on 2019-05-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0007_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('xblock_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('goal', models.CharField(blank=True, max_length=40)),
                ('standard', models.IntegerField(blank=True, default=0)),
                ('subject', models.CharField(blank=True, max_length=20)),
                ('chapter', models.CharField(blank=True, max_length=50)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.IntegerField(blank=True, default=1)),
                ('marks', models.IntegerField(blank=True, default=3)),
                ('negativeMarks', models.IntegerField(blank=True, default=-1)),
                ('questionType', models.CharField(blank=True, max_length=20)),
                ('tags', models.CharField(default=None, max_length=1000)),
                ('question', models.CharField(default=None, max_length=5000)),
                ('option1', models.CharField(default=None, max_length=2000)),
                ('option2', models.CharField(default=None, max_length=2000)),
                ('option3', models.CharField(default=None, max_length=2000)),
                ('option4', models.CharField(default=None, max_length=2000)),
                ('option1_iscorrect', models.BooleanField(default=0)),
                ('option2_iscorrect', models.BooleanField(default=0)),
                ('option3_iscorrect', models.BooleanField(default=0)),
                ('option4_iscorrect', models.BooleanField(default=0)),
                ('explanation', models.CharField(blank=True, default=None, max_length=5000)),
            ],
        ),
    ]
