# Generated by Django 2.1.5 on 2019-07-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0010_exams_exams_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams_package',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_data.exams'),
        ),
    ]
