# Generated by Django 2.1.5 on 2019-07-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0011_auto_20190719_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='image_url',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='exams_package',
            name='image_url',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
