# Generated by Django 2.1.5 on 2019-07-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0012_auto_20190722_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams_package',
            name='topic_available',
            field=models.BooleanField(default=0),
        ),
    ]
