# Generated by Django 2.1.5 on 2019-07-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0013_exams_package_topic_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams_package',
            name='topic_available',
            field=models.BooleanField(default=1),
        ),
    ]
