# Generated by Django 2.1.5 on 2019-07-23 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0014_auto_20190722_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('exams_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_data.exams')),
            ],
        ),
    ]
