# Generated by Django 2.1.5 on 2019-07-23 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0015_test_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_sections',
            name='exams_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_data.exams_package'),
        ),
    ]
