# Generated by Django 2.1.5 on 2019-07-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0016_auto_20190723_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_sections',
            name='section_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
