# Generated by Django 2.1.5 on 2019-07-29 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_exam_info'),
        ('course_data', '0017_test_sections_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='chapter_updated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.exam_info')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_data.exams')),
                ('exams_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_data.exams_package')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='chapter_updated',
            unique_together={('course', 'exam', 'exams_package', 'chapter')},
        ),
    ]
