# Generated by Django 2.2.4 on 2019-10-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0022_auto_20191016_1727'),
        ('course_data', '0018_auto_20190729_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='live_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=60)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher_info')),
            ],
        ),
    ]
