# Generated by Django 2.2.4 on 2019-10-18 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190731_1506'),
        ('course_data', '0019_live_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='crashcourse_enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_data.live_courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_info')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
