# Generated by Django 2.2.4 on 2019-10-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_data', '0020_crashcourse_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_courses',
            name='course_name',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
